import { GoogleGenAI, Modality, Chat, GenerateContentResponse, GenerateContentResult, VideosOperationResponse } from "@google/genai";
import type { AspectRatio } from '../types';

// Do not create a new GoogleGenAI instance at the top level.
// Create it right before making an API call to ensure it uses the most up-to-date API key from the dialog.

// --- Image Generation ---
export const generateImage = async (prompt: string, aspectRatio: AspectRatio, numberOfImages: number): Promise<string[]> => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  const response = await ai.models.generateImages({
    model: 'imagen-4.0-generate-001',
    prompt,
    config: {
      numberOfImages,
      aspectRatio,
      outputMimeType: 'image/png',
    },
  });

  return response.generatedImages.map(img => `data:image/png;base64,${img.image.imageBytes}`);
};

// --- Image Editing ---
export const editImage = async (prompt: string, imageBase64: string, mimeType: string): Promise<string> => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        { inlineData: { data: imageBase64, mimeType } },
        { text: prompt },
      ],
    },
    config: {
      responseModalities: [Modality.IMAGE],
    },
  });

  const part = response.candidates?.[0]?.content?.parts?.[0];
  if (part?.inlineData) {
    return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
  }
  throw new Error("No image was generated by the model.");
};

// --- Video Generation ---
// Fix: A required parameter cannot follow an optional parameter. Moved aspectRatio before the optional image parameter.
export const generateVideo = async (prompt: string, aspectRatio: '16:9' | '9:16', image?: { base64: string; mimeType: string }): Promise<string> => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  
  let operation = await ai.models.generateVideos({
    model: 'veo-3.1-fast-generate-preview',
    prompt,
    ...(image && { image: { imageBytes: image.base64, mimeType: image.mimeType } }),
    config: {
      numberOfVideos: 1,
      resolution: '720p',
      aspectRatio,
    }
  });

  while (!operation.done) {
    await new Promise(resolve => setTimeout(resolve, 10000));
    operation = await ai.operations.getVideosOperation({ operation: operation });
  }

  const downloadLink = operation.response?.generatedVideos?.[0]?.video?.uri;
  if (!downloadLink) {
    throw new Error("Video generation failed or returned no link.");
  }

  const videoResponse = await fetch(`${downloadLink}&key=${process.env.API_KEY}`);
  if (!videoResponse.ok) {
    throw new Error(`Failed to download video: ${videoResponse.statusText}`);
  }
  const blob = await videoResponse.blob();
  return URL.createObjectURL(blob);
};

// --- Chat ---
export const createChat = (): Chat => {
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
    return ai.chats.create({
        model: 'gemini-2.5-flash',
    });
};

export const sendMessageWithGrounding = async (chat: Chat, message: string): Promise<GenerateContentResponse> => {
    return chat.sendMessage({
        message: message,
        config: {
            tools: [{ googleSearch: {} }]
        }
    });
};

// --- Content Writing ---
export const generateText = async (prompt: string, useThinkingMode: boolean): Promise<GenerateContentResponse> => {
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
    return ai.models.generateContent({
        model: 'gemini-2.5-pro',
        contents: prompt,
        ...(useThinkingMode && {
            config: {
                thinkingConfig: { thinkingBudget: 32768 }
            }
        })
    });
};